[[mmtk_julia]]
arch = "x86_64"
git-tree-sha1 = "3188f580d5463b32989d6c93aeb55667e39a189b"
libc = "glibc"
os = "linux"

    [[mmtk_julia.download]]
    sha256 = "dc0a63bff011e2994200b6f76cb71c4c12db2d19bc92bfd294bb16ff38be081a"
    url = "https://github.com/JuliaBinaryWrappers/mmtk_julia_jll.jl/releases/download/mmtk_julia-v0.31.1+0/mmtk_julia.v0.31.1.x86_64-linux-gnu.tar.gz"
