# Autogenerated wrapper script for mmtk_julia_jll for x86_64-linux-gnu
export libmmtk_julia, mmtkMutator_h, mmtk_h

JLLWrappers.@generate_wrapper_header("mmtk_julia")
JLLWrappers.@declare_library_product(libmmtk_julia, "libmmtk_julia.so")
JLLWrappers.@declare_file_product(mmtkMutator_h)
JLLWrappers.@declare_file_product(mmtk_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmmtk_julia,
        "lib/libmmtk_julia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        mmtkMutator_h,
        "include/mmtkMutator.h",
    )

    JLLWrappers.@init_file_product(
        mmtk_h,
        "include/mmtk.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
